# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build WINDOWS wheels
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
     - uses: actions/checkout@v1
     - uses: msys2/setup-msys2@v2
       with:
        update: true
        path-type: inherit
        install: mingw-w64-ucrt-x86_64-gcc
                 mingw-w64-ucrt-x86_64-gcc-fortran
                 mingw-w64-ucrt-x86_64-cmake
     - run: echo "MSYSTEM=UCRT64" >> $GITHUB_ENV
     - run: echo "MADX_VERSION=$(cat MADX_VERSION)" >> $GITHUB_ENV
     - uses: conda-incubator/setup-miniconda@v2
       with:
         miniconda-version: "latest"
         auto-update-conda: true
         add-pip-as-python-dependency: true
         python-version: ${{ matrix.python-version }}
     - name: Installing required conda packages
       run: |
         conda install -c default -c anaconda -c "numpy<=1.18" libpython
     - name: Building for test
       run: |
         pip install -e .
     - name: Testing build
       run: |
         python docs/tutorial/example.py
     - name: Creating wheels
       run: |
         python setup.py bdist_wheel
     - uses: actions/upload-artifact@v2
       with:
         path: ./dist/*.whl
     - uses: actions/upload-artifact@v2
       with:
         path: ./dist/*.tar.gz
     - name: List directory contents
       run: |
         ls -l ./dist
