# .github/workflows/my-build.yml
name: Debugging with SSH
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v1
     - uses: conda-incubator/setup-miniconda@v2
       with:
         auto-update-conda: true
         python-version: 3.7
     - name: Start SSH session
       uses: luchihoratiu/debug-via-ssh@main
       with:
         NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
         SSH_PASS: ${{ secrets.SSH_PASS }} 
