# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build LINUX wheels on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.12.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: "cp27-* pp27-* cp35-* pp35-* pp*"  # skip Python 2.7 wheels
          CIBW_TEST_COMMAND: "python {project}/docs/tutorial/example.py"
      
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
      - name: List directory contents
        run: |
          ls -l ./dist