name: Build_Windows

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.7.0
        # to supply options, put them in 'env', like:
        env:
          CIBW_SKIP: "cp27-* pp27-* cp35-* pp35-*"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl