name: Build_Windows

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      # - name: Provide GCC on Windows
        # if: ${{ runner.os == 'Windows' }}
        # uses: msys2/setup-msys2@v2
      # - name: Tell distutils to use mingw on Windows
        # if: ${{ runner.os == 'Windows' }}
        # run: echo "[build]`ncompiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.7.0
        # to supply options, put them in 'env', like:
        env:
          CIBW_SKIP: "cp27-* pp27-* cp35-* pp35-*"
          # CIBW_BEFORE_BUILD_WINDOWS: vcpkg install getopt && vcpkg integrate install && vcpkg export getopt --raw && dir
          CIBW_BEFORE_ALL_WINDOWS: >
            vcpkg update &&
            vcpkg install getopt-win32 &&
            vcpkg integrate install
          
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl