# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build WINDOWS wheels
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8","3.9"]
    steps:
     - uses: actions/checkout@v1
     - uses: conda-incubator/setup-miniconda@v2
       with:
         miniconda-version: "latest"
         auto-update-conda: true
         add-pip-as-python-dependency: true
         python-version: ${{ matrix.python-version }}
     - name: Installing required conda packages
       run: |
         conda install -c default -c anaconda -c msys2 numpy libpython m2w64-toolchain
     - name: Building for test
       run: |
         pip install -e .
     - name: Testing build
       run: |
         python docs/tutorial/example.py
     - name: Creating wheels
       run: |
         python setup.py bdist_wheel
     - uses: actions/upload-artifact@v2
       with:
         path: ./dist/*.whl
     - uses: actions/upload-artifact@v2
       with:
         path: ./dist/*.tar.gz
     - name: List directory contents
       run: |
         ls -l ./dist
